project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - framework.qmd
    - literature-reviews/
    - recommendations.qmd
    - about.qmd
    - case-studies/
    - position-papers/

website:
  title: "DISTRIBUTED PREPAREDNESS"
  description: "Living companion on preparedness infrastructure, offline connectivity, open hardware, and distributed manufacturing: framework, case studies, extended literature review, and recommendations."
  navbar:
    left:
      - href: framework.qmd
        text: FRAMEWORK      
      - href: literature-reviews/index.qmd
        text: "LITERATURE REVIEWS"
      - href: case-studies/index.qmd
        text: "CASE STUDIES"
      - href: position-papers/index.qmd
        text: "POSITION PAPERS"
      - href: recommendations.qmd
        text: RECOMMENDATIONS
      - href: about.qmd
        text: ABOUT
  page-footer:
    center: "Knowledge Base for *Distributed Preparedness* first established in 2026 with support from the [Offline Internet Consortium](https://www.offlineinternet.org/)· [Reference library](https://www.zotero.org/groups/6184418/distributed_disaster_response/library)"

format:
  html:
    theme: [cosmo, styles.scss]
    toc: true
    link-external-newwindow: true

bibliography: references.bib
